In [2]:
from mxnet import autograd, nd

x = nd.arange(4).reshape(4, 1)
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [3]:
x.attach_grad()

In [14]:
print(autograd.is_training())
with autograd.record():
    y = 2 * nd.dot(x.T, x)
    print(autograd.is_training())
print(autograd.is_training())
y.backward()

assert (x.grad - 4 * x).norm().asscalar() == 0
print((x.grad - 4 * x).norm())
x.grad

False
True
False

[0.]
<NDArray 1 @cpu(0)>



[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [20]:
def f(a):
    b = a * 2
    while b.norm().asscalar() < 1000:
        b = b * 2
    if b.sum().asscalar() > 0:
        c = b
    else:
        c = 100 * b
    return c


a = nd.random.normal(shape=2)
print(a)
a.attach_grad()
with autograd.record():
    c = f(a)
c.backward()
print(a.grad)
a.grad == c / a


[-0.5459446 -2.3556297]
<NDArray 2 @cpu(0)>

[51200. 51200.]
<NDArray 2 @cpu(0)>



[1. 1.]
<NDArray 2 @cpu(0)>

In [28]:
from mxnet import nd
# help(autograd)
# autograd??

x = nd.array([[0, 0, 0], [2, 2, 2]])
y = x.ones_like()
y


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>