In [1]:
from mxnet import ndarray as nd

In [3]:
nd.zeros((3, 4))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [6]:
nd.ones((3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [17]:
nd.array([[1, 2], [2, 3]])


[[1. 2.]
 [2. 3.]]
<NDArray 2x2 @cpu(0)>

In [20]:
x = nd.arange(12)

X = x.reshape((3, 4)) 
x, X

(
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 <NDArray 12 @cpu(0)>, 
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]
 <NDArray 3x4 @cpu(0)>)

In [22]:
Y = nd.random_normal(0, 1, shape=(3, 4))
Y


[[ 0.5035904  -1.189445   -0.55021375 -1.5918757 ]
 [-1.1081947   0.0787202  -0.9185634  -0.74571437]
 [-1.2080863   1.8140212  -1.522743   -2.515245  ]]
<NDArray 3x4 @cpu(0)>

In [13]:
y.shape

(3, 4)

In [15]:
y.size

12

In [24]:
X + Y


[[ 0.5035904  -0.18944502  1.4497862   1.4081243 ]
 [ 2.8918052   5.07872     5.0814366   6.254286  ]
 [ 6.791914   10.814021    8.477257    8.484755  ]]
<NDArray 3x4 @cpu(0)>

In [25]:
X * Y


[[  0.          -1.189445    -1.1004275   -4.775627  ]
 [ -4.432779     0.39360103  -5.5113807   -5.2200007 ]
 [ -9.66469     16.32619    -15.22743    -27.667694  ]]
<NDArray 3x4 @cpu(0)>

In [26]:
X / Y


[[ 0.        -0.8407282 -3.6349509 -1.8845693]
 [-3.609474  63.516094  -6.5319386 -9.386972 ]
 [-6.6220436  4.9613533 -6.567096  -4.3733315]]
<NDArray 3x4 @cpu(0)>

In [28]:
Y.exp() # 按元素做指数运算


[[1.6546515  0.30439016 0.5768265  0.20354347]
 [0.33015445 1.0819016  0.39909196 0.47439528]
 [0.2987685  6.1350684  0.21811278 0.08084311]]
<NDArray 3x4 @cpu(0)>

In [30]:
nd.dot(X, Y.T)


[[ -7.0655     -3.9955497  -8.7772   ]
 [-18.377275  -14.770559  -22.50541  ]
 [-29.689053  -25.545568  -36.233624 ]]
<NDArray 3x3 @cpu(0)>

In [32]:
nd.concat(X, Y, dim=0), nd.concat(X, Y, dim=1)

(
 [[ 0.          1.          2.          3.        ]
  [ 4.          5.          6.          7.        ]
  [ 8.          9.         10.         11.        ]
  [ 0.5035904  -1.189445   -0.55021375 -1.5918757 ]
  [-1.1081947   0.0787202  -0.9185634  -0.74571437]
  [-1.2080863   1.8140212  -1.522743   -2.515245  ]]
 <NDArray 6x4 @cpu(0)>, 
 [[ 0.          1.          2.          3.          0.5035904  -1.189445
   -0.55021375 -1.5918757 ]
  [ 4.          5.          6.          7.         -1.1081947   0.0787202
   -0.9185634  -0.74571437]
  [ 8.          9.         10.         11.         -1.2080863   1.8140212
   -1.522743   -2.515245  ]]
 <NDArray 3x8 @cpu(0)>)

In [34]:
X == Y


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [35]:
X.sum()


[66.]
<NDArray 1 @cpu(0)>

In [36]:
X.norm().asscalar()

22.494442

In [38]:
A = nd.arange(3).reshape((3, 1))
B = nd.arange(2).reshape((1, 2))
A, B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [41]:
X[1:3, 2:4]


[[ 6.  7.]
 [10. 11.]]
<NDArray 2x2 @cpu(0)>

In [43]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [47]:
Z = Y.zeros_like()
before = id(Z)
Z[:] = X + Y
id(Z) == before

True

In [49]:
nd.elemwise_add(X, Y, out=Z)
id(Z) == before

True

In [51]:
before = id(X)
X += Y
id(X) == before

True

In [53]:
import numpy as np

P = np.ones((2, 3))
D = nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [54]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)